---
kind: pipeline
type: docker
name: tests

platform:
  os: linux
  arch: arm

steps:
  - name: Build
    image: haxe:4.2.4
    commands:
      - haxelib install --always build.hxml
      - haxe build.hxml
  - name: Composer install
    image: composer
    commands:
      - composer install
  - name: Run Tests on PHP7
    image: php:7-cli-alpine
    depends_on:
      - Composer install
      - Build
    commands:
      - php ./bin/tests/index.php
  - name: Run Tests on PHP8
    image: php:8-cli-alpine
    depends_on:
      - Composer install
      - Build
    commands:
      - php ./bin/tests/index.php

---
kind: pipeline
name: release

steps:
  - name: Zip Library
    image: alpine:3.15.2
    commands:
      - apk add zip
      - zip -r library.zip src *.md *.json README
  - name: Haxelib Publish
    image: haxe:4.2.4
    commands:
      - haxelib submit library.zip $HAXELIB_PASSWORD --always

trigger:
  event:
  - tag

depends_on:
- tests
---
kind: signature
hmac: 1e99b61e0166b1a3e530db3fa3ec0a3081c510691b65bfe10d2ea846bb64f92a

...
