kind: pipeline
type: docker

steps:
  - name: Build
    image: haxe:4.2.1
    commands:
      - haxelib install --always build.hxml
      - haxe build.hxml
  - name: Composer install
    image: composer
    commands:
      - composer install
  - name: Run Tests
    image: php:cli-alpine
    commands:
      - php ./bin/tests/index.php
