version: 22
jobs:
- name: Build
  steps:
  - !CheckoutStep
    name: Checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Check Style
    runInContainer: true
    image: haxe:4.2.4
    interpreter: !DefaultInterpreter
      commands:
      - haxelib install --always --quiet checkstyle
      - haxelib run checkstyle -s src --exitcode
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Build
    runInContainer: true
    image: haxe:4.2.4
    interpreter: !DefaultInterpreter
      commands:
      - haxelib install --always --quiet build.hxml
      - haxe build.hxml
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: Composer Install
  steps:
  - !CheckoutStep
    name: Checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Composer Install
    runInContainer: true
    image: composer
    interpreter: !DefaultInterpreter
      commands:
      - composer install
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  caches:
  - key: haxe-gql-vendor
    path: vendor
  timeout: 3600
- name: NPM install
  steps:
  - !CommandStep
    name: NPM Install
    runInContainer: true
    image: node:17-alpine3.14
    interpreter: !DefaultInterpreter
      commands:
      - npm install graphql
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  caches:
  - key: haxe-gql-node-modules
    path: node_modules
  timeout: 3600
- name: Run Tests on PHP
  steps:
  - !CommandStep
    name: Run Tests on PHP7
    runInContainer: true
    image: php:7-cli-alpine
    interpreter: !DefaultInterpreter
      commands:
      - php ./bin/tests/index.php
    useTTY: false
    condition: ALWAYS
  - !CommandStep
    name: Run Tests on PHP8
    runInContainer: true
    image: php:8-cli-alpine
    interpreter: !DefaultInterpreter
      commands:
      - php ./bin/tests/index.php
    useTTY: false
    condition: ALWAYS
  triggers:
  - !BranchUpdateTrigger {}
  jobDependencies:
  - jobName: Build
    requireSuccessful: true
    artifacts: bin/**
  - jobName: Composer Install
    requireSuccessful: true
    artifacts: vendor/**
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: Run Tests on NodeJS
  steps:
  - !CommandStep
    name: Run Tests on NodeJS
    runInContainer: true
    image: node:17-alpine3.14
    interpreter: !DefaultInterpreter
      commands:
      - node ./bin/tests.js
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger {}
  jobDependencies:
  - jobName: Build
    requireSuccessful: true
    artifacts: bin/**
  - jobName: NPM install
    requireSuccessful: true
    artifacts: node_modules/**
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
