package graphql;

import graphql.externs.ClientAware;
import haxe.Exception;

/**
    GraphQL compatible error, thrown by validators generated by the `FieldTypeBuilder`
**/
@:keep class GraphQLError extends Exception implements ClientAware {
    var category:String;
    var clientSafe:Bool;

    public function new(message:String, category = "generic", clientSafe = true) {
        super(message);
        this.category = category;
        this.clientSafe = clientSafe;
    }

    function isClientSafe() : Bool {
        return clientSafe;
    }

    function getCategory() : String {
        return category;
    }
}
